### PR TITLE
Changes made for Bookings to match DATEV-Format V700

### PR DESCRIPTION
**Pull request by sweimann**
- Changed the version information in DataCategories for Bookings
- Changed the verison information for the export Datev-File to 700.
- Added new header columns to the BookingRow Header
- Added new fields to the BookingRow (Fälligkeit, Generalumkehr, Steuersatz, Land) and added the matching validation rules

For further information please read: [DATEV-Document Library](https://apps.datev.de/dnlexka/document/1003221#D153122393655169547)

### CODE REVIEW

**Comment by IInvocation** [comment]
Hi,

thanks for the contribution. I briefly checked the changes - and generally - they would be fine by me - if there was no version change. Currently - i'll have to assume this would be breaking for other exports, since the current changes generally change the version number - allthough only BookingRows were adapted.

So - generally: i see 2 approaches here:
a) Move version and compatibility generally to 7.0
b) Add possibility to choose between versions

Checking the current documentation - it seems using the version number - the general changes make backward-compatibility possible so it should be ok (and less work intensive) to just pick possibility a).
(If anyone opposes: Please tell me! (i'm only using the library as a normal end-user)

I'll check things in detail this weekend and will probably have to add the other changes from v5 to v7 before merging anything.

**Comment by XF9** [comment]
Hi, are there any plans on merging this one in the near future? Or what has to be done to continue with it?

**Comment by IInvocation** [comment]
Hi, 
i forgot about the changes i planned here.

Generally: The request updated the general version to 700, while only implementing v700 for Bookings which is why i didnt want to merge it. I'd easily accept a merge-requests that completely upgrades to v700 - but personally - i want to make things easier in the future and don't want to keep the same approach)

As can be seen in the new feature-branch - i just started to change things a little, since actually by now: it's difficult to implement new changes because as of now it's difficult to see whtats new, whats old and what actually needs changes in comparison to the official documentation.

As of now - i'm trying to use the orignal format-files in combination with existing code to enable having mutiple supported versions using the same classes. (Headers completely created from format-files, data-rows using attributes to associate properties with the original format-files to create the output - perhaps even leveraging the FormatFiles for validation)

I'm planning to remove the "ToRow"-method of IDatevRow and use IVersionDatevRow.ToRow(DataCategoryVersion) in the future with a more dynamic approach to generate actual output. (Don't wanna mess with those endlessly long concatenations)

It's probably going to take a little time - but now i'm working on it.

**Comment by IInvocation** [comment]
As of version 1.1.3 i've implemented v700 for Addresses, Bookings and TermsOfPayment using the described method.
Also - i added all of the usable datev-fields. (If you find problems - please let me know)

**Pull request closed without merging**
